/* Level definitions for CANARY MINE — 12 C-safety lessons */

window.BUFFER_SIZE_DEFAULT = 8;

window.LEVELS = [
  {
    id: 1,
    name: "SAFE COPY",
    binary: "bin/L01_safe_copy",
    source: "L01_safe_copy.c",
    compile: "cc -O0 -fstack-protector-strong -o bin/L01_safe_copy lessons/L01_safe_copy.c",
    objective: "Run L01: type a SHORT name (≤7 chars). Canary stays alive.",
    dialogue:
      "Lesson L01 — strncpy into buf[8] with protector ON. Keep cargo short so the bird never sees toxic gas.",
    hint: "Try: alice",
    guardOn: true,
    bufferSize: 8,
    unlockNextOn: "safe",
    termIntro: [
      { cls: "sys", text: "# L01 — lessons/L01_safe_copy.c" },
      { cls: "cyan", text: "$ cc -fstack-protector-strong -o bin/L01_safe_copy lessons/L01_safe_copy.c" },
      { cls: "cyan", text: "$ ./bin/L01_safe_copy" },
      { cls: "sys", text: "argv[1] name:" },
    ],
    successDialogue:
      "Binary exits 0. Buffer held the copy. Stack canary untouched — this is what safe C looks like.",
    failDialogue: "Too long for buf[8]. Use ≤7 printable chars (+ NUL).",
  },
  {
    id: 2,
    name: "STRCPY SMASH",
    binary: "bin/L02_strcpy_overflow",
    source: "L02_strcpy_overflow.c",
    compile: "cc -O0 -fstack-protector-strong -o bin/L02_strcpy_overflow lessons/L02_strcpy_overflow.c",
    objective: "Overflow with strcpy — watch *** stack smashing detected ***.",
    dialogue:
      "L02 uses strcpy with no bounds. Flood past 8 bytes. The bird dies so RET doesn't get hijacked.",
    hint: "Type 12+ A's: AAAAAAAAAAAA",
    guardOn: true,
    bufferSize: 8,
    unlockNextOn: "smash",
    termIntro: [
      { cls: "sys", text: "# L02 — strcpy is unbounded" },
      { cls: "err", text: "strcpy(buf, src); /* UNSAFE */" },
      { cls: "cyan", text: "$ ./bin/L02_strcpy_overflow" },
      { cls: "sys", text: "payload:" },
    ],
    successDialogue:
      "Compiler-inserted canary caught the smash. Process aborted via __stack_chk_fail — EXIT saved.",
    failDialogue: "Need an overflow (>8 chars) to trip the canary.",
  },
  {
    id: 3,
    name: "STACK LAYOUT",
    binary: "bin/L03_stack_layout",
    source: "L03_stack_layout.c",
    compile: "cc -O0 -fstack-protector-strong -o bin/L03_stack_layout lessons/L03_stack_layout.c",
    objective: "Overflow again. Map mine zones → real stack slots.",
    dialogue:
      "L03 prints the buffer address. Overflow grows toward higher addresses: buf → canary → RBP → RET.",
    hint: "Smash with 12+ chars and watch the STACK FRAME panel.",
    guardOn: true,
    bufferSize: 8,
    unlockNextOn: "smash",
    highlightStack: true,
    termIntro: [
      { cls: "sys", text: "# L03 — layout: [buf 8][canary][rbp][ret]" },
      { cls: "hl", text: "low addr ──────────────────────────► high addr" },
      { cls: "cyan", text: "$ ./bin/L03_stack_layout" },
      { cls: "sys", text: "payload:" },
    ],
    successDialogue:
      "Same C bug, now with a memory map. Canary is the tripwire before saved RIP.",
    failDialogue: "Overflow to light up the stack climb.",
  },
  {
    id: 4,
    name: "GETS BANNED",
    binary: "bin/L04_gets_banned",
    source: "L04_gets_banned.c",
    compile: "cc -O0 -fstack-protector-strong -o bin/L04_gets_banned lessons/L04_gets_banned.c",
    objective: "gets() cannot bound input — overflow on purpose.",
    dialogue:
      "L04 calls gets(buf). Removed from C11 for a reason: it will read until newline with no size limit. Flood it.",
    hint: "Type a long line, e.g. AAAAAAAAAAAAA",
    guardOn: true,
    bufferSize: 8,
    unlockNextOn: "smash",
    termIntro: [
      { cls: "sys", text: "# L04 — gets() is banned (C11 removed it)" },
      { cls: "err", text: "gets(buf); /* NEVER */" },
      { cls: "hl", text: "prefer: fgets(buf, sizeof buf, stdin);" },
      { cls: "cyan", text: "$ ./bin/L04_gets_banned" },
      { cls: "sys", text: "Enter name:" },
    ],
    successDialogue:
      "Even with a canary, gets() is indefensible. Fix the API — don't rely on the bird alone.",
    failDialogue: "gets() needs a long line to overflow. Use >8 characters.",
  },
  {
    id: 5,
    name: "SIZE MISMATCH",
    binary: "bin/L05_size_mismatch",
    source: "L05_size_mismatch.c",
    compile: "cc -O0 -fstack-protector-strong -o bin/L05_size_mismatch lessons/L05_size_mismatch.c",
    objective: "Tiny buf[8], huge staging buffer — mismatch overflow.",
    dialogue:
      "L05 fgets into big[64] then strcpy into buf[8]. Size mismatch is a classic C footgun. Overflow it.",
    hint: "Enter more than 8 characters.",
    guardOn: true,
    bufferSize: 8,
    unlockNextOn: "smash",
    termIntro: [
      { cls: "sys", text: "# L05 — char buf[8]; char big[64]; strcpy(buf, big);" },
      { cls: "err", text: "destination smaller than source capacity" },
      { cls: "cyan", text: "$ ./bin/L05_size_mismatch" },
      { cls: "sys", text: "Enter data:" },
    ],
    successDialogue:
      "Matching sizes (or copying with an explicit bound) prevents this class of bug.",
    failDialogue: "Need >8 chars so strcpy blows past buf[8].",
  },
  {
    id: 6,
    name: "EPILOGUE",
    binary: "bin/L06_epilogue_check",
    source: "L06_epilogue_check.c",
    compile: "cc -O0 -fstack-protector-strong -o bin/L06_epilogue_check lessons/L06_epilogue_check.c",
    objective: "Overflow, then read the function epilogue canary check.",
    dialogue:
      "L06: before ret, the compiler compares the canary. Mismatch → __stack_chk_fail / abort. Watch the disassembly-style log.",
    hint: "Overflow once. Study the epilogue lines in the terminal.",
    guardOn: true,
    bufferSize: 8,
    unlockNextOn: "smash",
    showEpilogue: true,
    termIntro: [
      { cls: "sys", text: "# L06 — epilogue check before ret" },
      { cls: "cyan", text: "$ ./bin/L06_epilogue_check" },
      { cls: "sys", text: "payload:" },
    ],
    successDialogue:
      "Epilogue: load canary → xor with thread secret → jnz fail. The bird's death is the signal.",
    failDialogue: "Overflow to force the epilogue check to fail.",
  },
  {
    id: 7,
    name: "GUARD OFF",
    binary: "bin/L07_guard_off",
    source: "L07_guard_off.c",
    compile: "cc -O0 -fno-stack-protector -o bin/L07_guard_off lessons/L07_guard_off.c",
    objective: "Same overflow compiled with -fno-stack-protector. EXIT falls.",
    dialogue:
      "L07 disabled the bird. Overflow deep enough to hit RET. Silence instead of alarm — control-flow hijack.",
    hint: "Use 20+ characters so overflow reaches the return address.",
    guardOn: false,
    bufferSize: 8,
    unlockNextOn: "hijack",
    termIntro: [
      { cls: "sys", text: "# L07 — cc -fno-stack-protector" },
      { cls: "err", text: "warning: stack canary disabled" },
      { cls: "cyan", text: "$ ./bin/L07_guard_off" },
      { cls: "sys", text: "payload:" },
    ],
    successDialogue:
      "No canary → corrupted RET. Never ship -fno-stack-protector except for rare deliberate experiments.",
    failDialogue: "Push deeper (16–20+ chars) to overwrite the return address.",
  },
  {
    id: 8,
    name: "OFF-BY-ONE",
    binary: "bin/L08_off_by_one",
    source: "L08_off_by_one.c",
    compile: "cc -O0 -fstack-protector-strong -o bin/L08_off_by_one lessons/L08_off_by_one.c",
    objective: "Type exactly 8 chars — buggy <= loop writes one past the end.",
    dialogue:
      "L08's loop uses <= and can write one byte past buf[7]. Off-by-ones often nick the canary's edge.",
    hint: "Type exactly 8 characters, e.g. ABCDEFGH",
    guardOn: true,
    bufferSize: 8,
    unlockNextOn: "offbyone",
    mode: "offbyone",
    termIntro: [
      { cls: "sys", text: "# L08 — for (i = 0; i <= n && i <= 8; i++) buf[i] = src[i];" },
      { cls: "err", text: "off-by-one: one extra write" },
      { cls: "cyan", text: "$ ./bin/L08_off_by_one" },
      { cls: "sys", text: "input (aim for len==8):" },
    ],
    successDialogue:
      "One extra byte is enough to corrupt a neighbor (often canary low bits). Bounds need <, not <=.",
    failDialogue: "Use exactly 8 characters to trigger the off-by-one path.",
  },
  {
    id: 9,
    name: "STRNCPY NUL",
    binary: "bin/L09_strncpy_pitfall",
    source: "L09_strncpy_pitfall.c",
    compile: "cc -O0 -fstack-protector-strong -o bin/L09_strncpy_pitfall lessons/L09_strncpy_pitfall.c",
    objective: "Type 8+ chars — strncpy may omit the terminating NUL.",
    dialogue:
      "L09: strncpy(buf, src, 8) with len≥8 leaves buf without '\\0'. printf then walks off the end. C string safety matters.",
    hint: "Type 8 or more characters, e.g. HHHHHHHH",
    guardOn: true,
    bufferSize: 8,
    unlockNextOn: "nul",
    mode: "nul",
    termIntro: [
      { cls: "sys", text: "# L09 — strncpy without forced NUL" },
      { cls: "err", text: "strncpy(buf, src, 8); /* may omit \\0 */" },
      { cls: "hl", text: "fix: buf[sizeof buf - 1] = '\\0';" },
      { cls: "cyan", text: "$ ./bin/L09_strncpy_pitfall" },
      { cls: "sys", text: "string:" },
    ],
    successDialogue:
      "Always terminate. Or use APIs that guarantee NUL (snprintf, strlcpy where available).",
    failDialogue: "Need length ≥ 8 so strncpy fills the buffer without room for NUL.",
  },
  {
    id: 10,
    name: "LIBCANARY",
    binary: "bin/L10_libcanary",
    source: "L10_libcanary.c",
    compile: "cc -O0 -fstack-protector-strong -pthread -o bin/L10_libcanary lessons/L10_libcanary.c libcanary/canary.c",
    objective: "Safe name with a DERIVED canary (secret ⊕ frame) from libcanary.",
    dialogue:
      "L10 links your libcanary: canary_deriv / canary_check / canary_fail. Plant, use buffer, verify before return.",
    hint: "Keep it short (≤7 chars), e.g. miner",
    guardOn: true,
    derived: true,
    bufferSize: 8,
    unlockNextOn: "safe",
    extraSources: ["canary.c", "canary.h"],
    termIntro: [
      { cls: "sys", text: "# L10 — libcanary derived canary" },
      { cls: "hl", text: "canary = secret ^ ret ^ (frame * DEADBEEF)" },
      { cls: "cyan", text: "$ ./bin/L10_libcanary" },
      { cls: "sys", text: "name:" },
    ],
    successDialogue:
      "Manual SSP: derive → plant → check → fail path. A leaked canary from one frame won't trivially replay into another.",
    failDialogue: "Stay ≤7 characters so the derived canary check passes.",
  },
  {
    id: 11,
    name: "SAFE FGETS",
    binary: "bin/L11_safe_fgets",
    source: "L11_safe_fgets.c",
    compile: "cc -O0 -fstack-protector-strong -o bin/L11_safe_fgets lessons/L11_safe_fgets.c",
    objective: "Use the safe pattern — short name, fgets + snprintf mindset.",
    dialogue:
      "L11 is the rewrite: fgets(name, sizeof name, stdin) + snprintf. Bound every read and format. Type a short name.",
    hint: "Any short name ≤15 chars works, e.g. bob",
    guardOn: true,
    bufferSize: 16,
    unlockNextOn: "safe",
    mode: "safe_api",
    termIntro: [
      { cls: "sys", text: "# L11 — defender pattern" },
      { cls: "ok", text: "fgets(name, sizeof name, stdin);" },
      { cls: "ok", text: "snprintf(out, sizeof out, \"hello, %s\", name);" },
      { cls: "cyan", text: "$ ./bin/L11_safe_fgets" },
      { cls: "sys", text: "Enter name:" },
    ],
    successDialogue:
      "This is shippable C: bounded input, bounded output, protector still ON as belt-and-suspenders.",
    failDialogue: "Keep the name within the fgets limit (≤15 chars here).",
  },
  {
    id: 12,
    name: "HARDENING",
    binary: "bin/L12_hardening",
    source: "L12_hardening.c",
    compile: "cc -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -o bin/L12_hardening lessons/L12_hardening.c",
    objective: "Final run: short name under full hardening flags.",
    dialogue:
      "L12 checklist: -fstack-protector-strong, _FORTIFY_SOURCE=2, safe APIs, never disable canaries in prod. Enter a short name to finish the mine.",
    hint: "Type a short name like: clear",
    guardOn: true,
    bufferSize: 16,
    unlockNextOn: "safe",
    mode: "hardened",
    termIntro: [
      { cls: "sys", text: "# L12 — hardening checklist binary" },
      { cls: "ok", text: "[x] -fstack-protector-strong" },
      { cls: "ok", text: "[x] -D_FORTIFY_SOURCE=2" },
      { cls: "ok", text: "[x] fgets/snprintf — not gets/strcpy" },
      { cls: "cyan", text: "$ ./bin/L12_hardening" },
      { cls: "sys", text: "short-name:" },
    ],
    successDialogue:
      "Mission complete. Canaries are one layer — pair them with safe APIs and fortified builds.",
    failDialogue: "Stay within the hardened buffer (≤15 chars).",
  },
];
