/* 6 defensive challenges — one goal, one action each */

window.LEVELS = [
  {
    id: 1,
    name: "FIND THE BIRD",
    kind: "find",
    goal: "Name what sits between the BUFFER and the EXIT.",
    prompt: "Look at the mine. The yellow bird guards the exit. Type its name.",
    hint: "Type: canary",
    answer: "canary",
    guardOn: true,
    scene: "idle",
    source: "L01_safe_copy.c",
    binary: "bin/L01_safe_copy",
    success: "Yes. The canary sits between your buffer and the return address (EXIT).",
  },
  {
    id: 2,
    name: "SAFE CARGO",
    kind: "safe",
    goal: "Send a short name (≤7 chars). Keep the bird alive.",
    prompt: "Input goes into buffer[8]. Stay short so nothing reaches the canary.",
    hint: "Try: alice",
    guardOn: true,
    bufferSize: 8,
    scene: "idle",
    source: "L01_safe_copy.c",
    binary: "bin/L01_safe_copy",
    success: "Buffer held it. Canary untouched. Normal return through EXIT.",
  },
  {
    id: 3,
    name: "SMASH ALARM",
    kind: "smash",
    goal: "Overflow on purpose (>8 chars). Watch the alarm — don't bypass it.",
    prompt: "Flood the buffer. When gas hits the bird, the process aborts before EXIT is used.",
    hint: "Type 12+ letters, e.g. AAAAAAAAAAAA",
    guardOn: true,
    bufferSize: 8,
    scene: "idle",
    source: "L02_strcpy_overflow.c",
    binary: "bin/L02_strcpy_overflow",
    success: "*** stack smashing detected *** — bird dies, EXIT is saved. That's the point.",
  },
  {
    id: 4,
    name: "NO GUARD",
    kind: "hijack",
    goal: "Same overflow, but canary disabled. See EXIT fall.",
    prompt: "Guard is OFF (-fno-stack-protector). Overflow deep enough to hit the return address.",
    hint: "Use 20+ characters so you reach RET.",
    guardOn: false,
    bufferSize: 8,
    scene: "noguard",
    source: "L07_guard_off.c",
    binary: "bin/L07_guard_off",
    success: "No bird → no alarm → RET corrupted. Canaries exist to stop this silence.",
  },
  {
    id: 5,
    name: "SPOT THE BUG",
    kind: "choice",
    goal: "Which line is the memory-safety bug?",
    prompt: "Pick the unsafe call. Canaries catch symptoms — this is the disease.",
    hint: "gets() and strcpy() don't know the buffer size.",
    guardOn: true,
    scene: "idle",
    source: "L04_gets_banned.c",
    binary: "bin/L04_gets_banned",
    choices: [
      { id: "a", label: 'printf("hello");', ok: false },
      { id: "b", label: "gets(buf);  /* unbounded read */", ok: true },
      { id: "c", label: "fgets(buf, sizeof buf, stdin);", ok: false },
    ],
    success: "gets() can't bound input. Fix the API — don't rely on the canary alone.",
  },
  {
    id: 6,
    name: "PICK THE FIX",
    kind: "choice",
    goal: "Which build/API combo is the defender pattern?",
    prompt: "Choose the option you'd ship.",
    hint: "Bounded I/O + stack protector + fortify.",
    guardOn: true,
    scene: "safe",
    source: "L12_hardening.c",
    binary: "bin/L12_hardening",
    choices: [
      {
        id: "a",
        label: "gets + strcpy, -fno-stack-protector",
        ok: false,
      },
      {
        id: "b",
        label: "fgets + snprintf, -fstack-protector-strong, _FORTIFY_SOURCE",
        ok: true,
      },
      {
        id: "c",
        label: "strcpy only — canary will save us",
        ok: false,
      },
    ],
    success: "Ship bounded APIs and keep the bird. Canary is a seatbelt, not a steering wheel.",
  },
];
