/* 6 defensive challenges — inspired by common SSP / canary facts (no bypass training) */

window.LEVELS = [
  {
    id: 1,
    name: "FIND THE BIRD",
    kind: "find",
    goal: "Name what the compiler plants between locals and the return address.",
    prompt: "Mine left→right: BUFFER → bird → EXIT. Stack right shows the same order upward.",
    hint: "Type: canary",
    answer: "canary",
    guardOn: true,
    scene: "idle",
    source: "L01_safe_copy.c",
    binary: "bin/L01_safe_copy",
    fact: "SSP plants a guard between selected locals and saved control data, then checks it in the epilogue.",
    success: "That bird is the stack canary / guard. Corrupt it and the epilogue refuses to use EXIT.",
  },
  {
    id: 2,
    name: "SAFE CARGO",
    kind: "safe",
    goal: "Send a short name (≤7 chars). Keep the guard intact.",
    prompt: "Input fills buffer[8] only. Stay short — nothing should touch the canary slot.",
    hint: "Try: alice",
    guardOn: true,
    bufferSize: 8,
    scene: "idle",
    source: "L01_safe_copy.c",
    binary: "bin/L01_safe_copy",
    fact: "A canary does not fix bad APIs — it only detects smash after the fact when the function returns.",
    success: "Guard unchanged → epilogue happy → normal return through EXIT.",
  },
  {
    id: 3,
    name: "SMASH ALARM",
    kind: "smash",
    goal: "Overflow (>8 chars) and watch __stack_chk_fail / abort. Observe only.",
    prompt: "Flood past the buffer into the canary. On return, mismatch → fail path. EXIT is not trusted.",
    hint: "Type 12+ letters, e.g. AAAAAAAAAAAA",
    guardOn: true,
    bufferSize: 8,
    scene: "idle",
    source: "L02_strcpy_overflow.c",
    binary: "bin/L02_strcpy_overflow",
    fact: "On mismatch the runtime calls __stack_chk_fail. The check runs before the saved return address is used.",
    success: "*** stack smashing detected *** — bird dies so EXIT isn't followed. That's the seatbelt firing.",
  },
  {
    id: 4,
    name: "NO GUARD",
    kind: "hijack",
    goal: "Same overflow with -fno-stack-protector. See EXIT fall in silence.",
    prompt: "No bird in the frame. Overflow deep enough to hit the return address.",
    hint: "Use 20+ characters so you reach RET.",
    guardOn: false,
    bufferSize: 8,
    scene: "noguard",
    source: "L07_guard_off.c",
    binary: "bin/L07_guard_off",
    fact: "Without a canary, a linear smash can reach saved control data with no epilogue alarm.",
    success: "No guard → no alarm → RET corrupted. Keep -fstack-protector-strong in real builds.",
  },
  {
    id: 5,
    name: "SPOT THE BUG",
    kind: "choice",
    goal: "Which line is the memory-safety bug?",
    prompt: "Canaries catch some overflows at return. The real fix is not writing past the buffer.",
    hint: "Unbounded reads/copies ignore destination size.",
    guardOn: true,
    scene: "idle",
    source: "L04_gets_banned.c",
    binary: "bin/L04_gets_banned",
    fact: "Terminator-style guards (NUL first on many glibc layouts) frustrate strcpy-style copies — but memcpy/read can still march past.",
    choices: [
      { id: "a", label: 'printf("hello");', ok: false },
      { id: "b", label: "gets(buf); / strcpy(dst, src);  /* no bound */", ok: true },
      { id: "c", label: "fgets(buf, sizeof buf, stdin);", ok: false },
    ],
    success: "Unbounded copy is the disease. The canary is a late symptom detector.",
  },
  {
    id: 6,
    name: "PICK THE FIX",
    kind: "choice",
    goal: "Which option is the defender pattern you'd ship?",
    prompt: "Pick bounded I/O plus modern stack protection.",
    hint: "fgets/snprintf + -fstack-protector-strong (+ fortify).",
    guardOn: true,
    scene: "safe",
    source: "L12_hardening.c",
    binary: "bin/L12_hardening",
    fact: "Prefer -fstack-protector-strong (or equivalent) and bounded APIs. A canary alone is not a substitute for correct sizes.",
    choices: [
      { id: "a", label: "gets + strcpy, -fno-stack-protector", ok: false },
      {
        id: "b",
        label: "fgets + snprintf, -fstack-protector-strong, _FORTIFY_SOURCE",
        ok: true,
      },
      { id: "c", label: "strcpy is fine — the canary will save us", ok: false },
    ],
    success: "Ship bounded APIs and keep the bird. Seatbelt + sober driving.",
  },
];
