#!/usr/bin/env python3
"""Bundle lesson C sources into game/lesson_bundle.js for the web UI."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSONS = ROOT / "lessons"
OUT = ROOT / "game" / "lesson_bundle.js"

FILES = [
    "L01_safe_copy.c",
    "L02_strcpy_overflow.c",
    "L03_stack_layout.c",
    "L04_gets_banned.c",
    "L05_size_mismatch.c",
    "L06_epilogue_check.c",
    "L07_guard_off.c",
    "L08_off_by_one.c",
    "L09_strncpy_pitfall.c",
    "L10_libcanary.c",
    "L11_safe_fgets.c",
    "L12_hardening.c",
    "common.h",
]


def main() -> None:
    bundle: dict[str, str] = {}
    for name in FILES:
        path = LESSONS / name
        bundle[name] = path.read_text(encoding="utf-8")
    # Also include libcanary header/source for L10 context
    bundle["canary.h"] = (ROOT / "libcanary" / "canary.h").read_text(encoding="utf-8")
    bundle["canary.c"] = (ROOT / "libcanary" / "canary.c").read_text(encoding="utf-8")

    OUT.write_text(
        "/* Auto-generated by tools/bundle_lessons.py — do not edit */\n"
        "window.LESSON_SOURCES = "
        + json.dumps(bundle, indent=2)
        + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({len(bundle)} files)")


if __name__ == "__main__":
    main()
